deployment:
  tasks:
    - export DEPLOYPATH=/home/tendax20/test.tendaxe.com
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH
    - composer install --no-dev --prefer-dist
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - chown -R username:username $DEPLOYPATH
    - chmod -R 775 $DEPLOYPATH/storage
    - chmod -R 775 $DEPLOYPATH/bootstrap/cache
